{
 "title": "test alertmanager",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "reconnection fail rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(alertmanager_cluster_reconnections_failed_total[1m])"
    }
   ]
  },
  {
   "title": "peer join rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(alertmanager_cluster_peers_joined_total[1m])"
    }
   ]
  },
  {
   "title": "failed peers rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(alertmanager_cluster_failed_peers[1m])"
    }
   ]
  },
  {
   "title": "reconnection rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(alertmanager_cluster_reconnections_total[1m])"
    }
   ]
  },
  {
   "title": "refresh join fail rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(alertmanager_cluster_refresh_join_failed_total[1m])"
    }
   ]
  }
 ]
}