{
 "title": "nomad client",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(nomad_client_unallocated_cpu,host)"
    }
   },
   {
    "name": "allocation",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_total_ticks{host=\"$host\"},task_group)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Allocated CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_allocated_cpu{host=\"$host\"} / (nomad_client_allocated_cpu{host=\"$host\"} + nomad_client_unallocated_cpu{host=\"$host\"})",
     "legendFormat": "Allocated CPU"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1 - rate(node_cpu_seconds_total{mode=\"idle\",instance=\"$host\"}[$__rate_interval]))",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_allocated_memory{host=\"$host\"} / (nomad_client_allocated_memory{host=\"$host\"} + nomad_client_unallocated_memory{host=\"$host\"})",
     "legendFormat": "Allocated Memory"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable_bytes{instance=\"$host\"} / node_memory_MemTotal_bytes{instance=\"$host\"} ",
     "legendFormat": "RAM Utilization"
    }
   ]
  },
  {
   "title": "Allocated Disk",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_allocated_disk{host=\"$host\"} / (nomad_client_allocated_disk{host=\"$host\"} + nomad_client_unallocated_disk{host=\"$host\"})",
     "legendFormat": "Allocated Disk"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - node_filesystem_avail_bytes{instance=\"$host\",fstype!=\"tmpfs\"} / node_filesystem_size_bytes{instance=\"$host\",fstype!=\"tmpfs\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "CPU % Usage per Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nomad_client_allocs_cpu_total_ticks{host=\"$host\"} / nomad_client_allocs_cpu_allocated{host=\"$host\"}",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Memory % Usage per Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nomad_client_allocs_memory_rss{host=\"$host\"} / nomad_client_allocs_memory_allocated{host=\"$host\"}",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$host\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "-rate(node_network_transmit_bytes_total{instance=\"$host\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "$allocation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "allocation",
   "collapsed": true,
   "panels": [
    {
     "title": "$allocation CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "nomad_client_allocs_cpu_allocated{task=\"$allocation\"} * 1000000",
       "legendFormat": "allocated"
      },
      {
       "expr": "nomad_client_allocs_cpu_total_ticks{task=\"$allocation\"} * 1000000",
       "legendFormat": "current"
      }
     ]
    },
    {
     "title": "$allocation Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nomad_client_allocs_memory_allocated{task=\"$allocation\"}",
       "legendFormat": "allocated"
      },
      {
       "expr": "nomad_client_allocs_memory_rss{task=\"$allocation\"}",
       "legendFormat": "current"
      }
     ]
    },
    {
     "title": "connect-proxy-$allocation CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "nomad_client_allocs_cpu_allocated{task=\"connect-proxy-$allocation\"} * 1000000",
       "legendFormat": "allocated"
      },
      {
       "expr": "nomad_client_allocs_cpu_total_ticks{task=\"connect-proxy-$allocation\"} * 1000000",
       "legendFormat": "current"
      }
     ]
    },
    {
     "title": "connect-proxy-$allocation Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nomad_client_allocs_memory_allocated{task=\"connect-proxy-$allocation\"}",
       "legendFormat": "allocated"
      },
      {
       "expr": "nomad_client_allocs_memory_rss{task=\"connect-proxy-$allocation\"}",
       "legendFormat": "current"
      }
     ]
    }
   ]
  }
 ]
}