{
 "title": "Tron Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(address) (tron_token_total_balance) / 1000000"
    }
   ]
  },
  {
   "title": "Holders",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(address) (tron_token_total_holders)"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(address) (tron_token_total_transactions)"
    }
   ]
  },
  {
   "title": "Klever Exchange",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(address) (tron_token_holder_balance{address=\"TKM9AYxWxRe7hESuWmKFXwcDjnb5cQK92E\"}) / 1000000",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Stake Wallet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(address) (tron_token_holder_balance{address=\"TUPmayJ5CWWKjYFVmML2ycKXMCbyKbgtML\"}) / 1000000",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Dev Wallet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(address) (tron_token_holder_balance{address=\"TBmKCtscG34xEgQdCTRMvRMKfyoABHqesx\"}) / 1000000",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Top Holders",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(address) (tron_token_holder_balance{address!~\"TBmKCtscG34xEgQdCTRMvRMKfyoABHqesx|TUPmayJ5CWWKjYFVmML2ycKXMCbyKbgtML|TKM9AYxWxRe7hESuWmKFXwcDjnb5cQK92E\"}) / 1000000",
     "legendFormat": "{{address}}"
    }
   ]
  }
 ]
}