name: Archive and upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: zip grafana-config.zip *

      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
  
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: latest
          artifacts: grafana-config.zip
          token: ${{ secrets.GITHUB_TOKEN }}
